name: mi_card
description: "Mi Card"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/photos/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Source Sans
      fonts:
        - asset: assets/fonts/Source Sans/SourceSans3-Italic-Variable.ttf
        - asset: assets/fonts/Source Sans/SourceSans3-VariableFont.ttf
